#!/usr/bin/env ruby
require 'logit'
require 'optparse'

options = {}
options[:debug]   = false
options[:verbose] = false
OptionParser.new do |opts|
  opts.banner = "Usage: graphit [options] data"

  opts.on("-d", "--[no-]debug", "Debug output") do |d|
    options[:debug] = d
  end

  opts.on("-v", "--[no-]verbose", "Run verbosely") do |v|
    options[:verbose] = v
  end
    
  opts.on("-o", "--output-file [file]", "Filename") do |of|
    options[:filename] = of
  end
  
end.parse!

options[:filename] ||= "data.log"

@incoming_data_point = 0
ARGF.each_line do |line|
  puts "Line: #{line}"
  @incoming_data_point = line.strip.split( " " ).first.to_f rescue 0
  puts "@incoming_data_point: #{@incoming_data_point}"
  break
end

Logit::Log.new( options ).load.log_value(@incoming_data_point).save